### ISSUE TITLE
cargo-embed is panicking at creating rttui on STM32 F746 disco board

### ISSUE THREAD

**Issue by mchodzikiewicz** [probe-rs/cargo-embed#267]
When using RTT like in docs:
```rust
#![no_std]
#![no_main]

use panic_halt as _;
use rtt_target::{rprintln, rtt_init_print};
use cortex_m_rt::entry;
use stm32f7xx_hal as hal;

#[cortex_m_rt::entry]
fn main() -> ! {
    rtt_init_print!();
    loop {
        rprintln!("Hello, world!");
    }
}
```
with 
```toml
[default.rtt]
# Whether or not an RTTUI should be opened after flashing.
enabled = true
```
I get panic
```
      Config default
      Target /home/mchodzikiewicz/projects/drum-shaker/target/thumbv7em-none-eabihf/debug/drum-shaker
    Finished flashing in 0.62s
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Uncategorized, message: "No such device or address" }', /home/mchodzikiewicz/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-embed-0.11.0/src/rttui/app.rs:105:27
stack backtrace:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Failed to initialize input reader" }', /home/mchodzikiewicz/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-embed-0.11.0/src/rttui/event.rs:41:54
   0: rust_begin_unwind
             at /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/result.rs:1617:5
   3: cargo_embed::rttui::app::App::new
   4: cargo_embed::main_try
   5: cargo_embed::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/result.rs:1617:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 101
```

I am using Linux Manjaro

I was able to attach to the gdb server stub and stop at breakpoint, so flashing and general connectiion is working

**Comment by mchodzikiewicz** [comment]
I am closing the issue because I have found the root cause - I configured IntelliJ's Rust plugin to run `cargo embed` as plugin's cargo command - `rttui` have been panicking because it tried to open stdin or something, but it was impossible because it was not attached to a proper console. Later on I just launched it in shell and it worked (and have forgotten that previously I have used the plugin)

I am kinda facepalming right now, but it might be worth adding a short note to the getting started guide
